[build]
command = "npm run build"
publish = "client/.next"
functions = "api/build"

[dev]
command = "npm run start"
functionsPort = 9000
targetPort = 3000
port = 8080
envFiles = [".env.development.local", ".env.local", ".env.development", ".env"]