import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
      </head>
      <body className={inter.className}>
        <aside>
          <div className='account-panel'>
            <div className='account-image'>
              <span className="material-symbols-outlined">person</span>
            </div>
            <nav className='account-navigation'>
              <Link href={'/messages'} title='Messages'><span className="material-symbols-outlined">mail</span></Link>
              <Link href={'/blogs/owned'} title='My Blogs'><span className="material-symbols-outlined">menu_book</span></Link>
              <Link href={'/terminal'} title='Terminal'><span className="material-symbols-outlined">terminal</span></Link>
              <Link href={'/logout'} title='Logout'><span className="material-symbols-outlined">logout</span></Link>
              <Link href={'/config'} title='Config'><span className="material-symbols-outlined">settings</span></Link>
            </nav>
          </div>
          <div className='menu-panel'>
            <nav className='main-navigation'>
              <Link href={'/'}><span className="material-symbols-outlined">home</span>Home</Link>
              <Link href={'/blogs'}><span className="material-symbols-outlined">menu_book</span>Blogs</Link>
              <Link href={'/categories'}><span className="material-symbols-outlined">category</span>Categories</Link>
              <Link href={'/users'}><span className="material-symbols-outlined">group</span>Users</Link>
            </nav>
            <nav className='sub-navigation'>
              <Link href={'/news'}><span className="material-symbols-outlined">breaking_news</span>News</Link>
              <Link href={'/about'}><span className="material-symbols-outlined">lightbulb</span>About Us</Link>
              <Link href={'/info'}><span className="material-symbols-outlined">info_i</span>Information</Link>
              <Link href={'/licence'}><span className="material-symbols-outlined">copyright</span>Licence</Link>
            </nav>
          </div>
        </aside>
        <main>
          <header>
            <h1>Hush Hush Diaries</h1>
          </header>
          <div className='viewer'>
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
